### ISSUE TITLE
Crash: SocketException

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Analytics-Android#4]
```

04-18 13:29:24.191 17989-18076/org.wordpress.android E/NosaraClient: Error while sending the events to the server
                                                                     java.net.SocketException: Software caused connection abort
                                                                         at java.net.PlainSocketImpl.socketConnect(Native Method)
                                                                         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
                                                                         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
                                                                         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
                                                                         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
                                                                         at java.net.Socket.connect(Socket.java:605)
                                                                         at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
                                                                         at com.android.okhttp.Connection.connectSocket(Connection.java:196)
                                                                         at com.android.okhttp.Connection.connect(Connection.java:172)
                                                                         at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
                                                                         at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
                                                                         at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
                                                                         at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
                                                                         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
                                                                         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
                                                                         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
                                                                         at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
                                                                         at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
                                                                         at com.automattic.android.tracks.TracksClient$3.run(TracksClient.java:235)
                                                                         at java.lang.Thread.run(Thread.java:761)
                                                                     	Suppressed: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x731a14fc00: I/O error during system call, Connection reset by peer
                                                                         at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                         at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
                                                                         at com.android.okhttp.Connection.connectTls(Connection.java:235)
                                                                         at com.android.okhttp.Connection.connectSocket(Connection.java:199)
                                                                         		... 12 more



```

**Comment by daniloercoli** [comment]
This is weird, since the socket exception is catched in Tracks, and logs are bumped fine. In fact, in the log above ,the error message is written here: https://github.com/Automattic/Automattic-Tracks-Android/blob/develop/AutomatticTracks/src/main/java/com/automattic/android/tracks/TracksClient.java#L259

**Comment by mzorz** [comment]
I know it's considered bad practice generally speaking but in this particular case where we just need to keep running, does it make sense to catch the general Exception ?

I also doubted when I saw it but no other exceptions appeared in logcat


It might be an isolated case though, will circle back here if I see it again

**Comment by daniloercoli** [comment]
> I know it's considered bad practice generally speaking but in this particular case where we just need to keep running, does it make sense to catch the general Exception ?

We're already catching the general `Exception` there :)
So I doubt the crash is due to Tracks. Maybe the app crashed in another thread?

**Comment by mzorz** [comment]
the thread says `04-18 13:29:24.191 17989-18076/org.wordpress.android E/NosaraClient: Error while sending the events to the server
                                                                     java.net.SocketException: Software caused connection abort`

¯\_(ツ)_/¯ what do you think?

**Comment by mzorz** [comment]
> We're already catching the general Exception there :)
> So I doubt the crash is due to Tracks. Maybe the app crashed in another thread?

My bad - double checked - closing
